import img1 from './assets/images/fi4.png'

import img2 from './assets/images/fi2.png'
import skirt1 from './assets/images/skirt1.png'
import img3 from './assets/images/fi3.png'
import shirt1 from './assets/images/shirt1.png'
import img4 from './assets/images/fi4.png'
import pajama1 from './assets/images/pajamas1.png'
import blank from './assets/images/blank.png'
import jacket1 from './assets/images/jacket1.png'
import socks1 from './assets/images/socks1.png'
import shoe1 from './assets/images/shoe1.png'
import shoe2 from './assets/images/shoe2.png'
import neck1 from './assets/images/neck1.png'
import neck2 from './assets/images/neck2.png'

const ClothesData = [
  {
    id: 1,
    src: [img1, blank, blank],
    alt: 'New Season Jacket',
    name: 'Soft Jacket',
    price: '$49.99',
    category: 'jackets',
  },
  {
    id: 2,
    src: [img2, blank, blank],
    alt: 'Elegant Tunic',
    name: 'Green Tunic',
    price: '$39.99',
    category: 'tunics',
  },
  {
    id: 3,
    src: [img3, blank, blank],
    alt: 'Trendy Coat',
    name: 'Camel Coat',
    price: '$69.99',
    category: 'coats',
  },
  {
    id: 4,
    src: [img4, blank, blank],
    alt: 'Chic Trousers',
    name: 'Beige Pants',
    price: '$34.99',
    category: 'pants',
  },
  {
    id: 5,
    src: [img4, blank, blank],
    alt: 'Chic Trousers',
    name: 'Beige Pants',
    price: '$34.99',
    category: 'scarves',
  },
  {
    id: 6,
    src: [img3, blank, blank],
    alt: 'Chic Trousers',
    name: 'Beige Pants',
    price: '$34.99',
    category: 'skirts',
  },
  {
    id: 7,
    src: [img3, blank, blank],
    alt: 'Chic Trousers',
    name: 'Beige Pants',
    price: '$34.99',
    category: 'skirts',
  },
  {
    id: 8,
    src: [img4, blank, blank],
    alt: 'Chic Trousers',
    name: 'Beige Pants',
    price: '$34.99',
    category: 'scarves',
  },
  {
    id: 9,
    src: [pajama1, blank, blank],
    alt: 'pajama1',
    name: 'Pink Pajama',
    price: '$24.99',
    category: 'pajamas',
  },
  {
    id: 9,
    src: [img1, blank, blank],
    alt: 'blank',
    name: 'Blue Pajama',
    price: '$27.99',
    category: 'pajamas',
  },
  {
    id: 10,
    src: [img2, blank, blank],
    alt: 'blank',
    name: 'yellow Pajama',
    price: '$15.99',
    category: 'pajamas',
  },
  {
    id: 11,
    src: [img3, blank, blank],
    alt: 'blank',
    name: 'white Pajama',
    price: '$12.99',
    category: 'pajamas',
  },
  {
    id: 12,
    src: [img4, blank, blank],
    alt: 'blank',
    name: 'white Pajama',
    price: '$12.99',
    category: 'pajamas',
  },
  {
    id: 13,
    src: [img2, blank, blank],
    alt: 'blank',
    name: 'white Pajama',
    price: '$12.99',
    category: 'pajamas',
  },
  {
    id: 14,
    src: [img2, blank, blank],
    alt: 'blank',
    name: 'white Pajama',
    price: '$12.99',
    category: 'pajamas',
  },
  {
    id: 15,
    src: [jacket1, blank, blank],
    alt: 'jacket1',
    name: 'jacket',
    price: '$62.99',
    category: 'jackets',
  },
  {
    id: 16,
    src: [shirt1, blank, blank],
    alt: 'shirt1',
    name: 'white shirt',
    price: '$30.99',
    category: 'shirts',
  },
  {
    id: 17,
    src: [shirt1, blank, blank],
    alt: 'shirt1',
    name: 'white shirt',
    price: '$25.99',
    category: 'shirts',
  },
  {
    id: 18,
    src: [shirt1, blank, blank],
    alt: 'shirt1',
    name: 'white shirt',
    price: '$25.99',
    category: 'shirts',
  },
  {
    id: 19,
    src: [shirt1, blank, blank],
    alt: 'shirt1',
    name: 'white shirt',
    price: '$25.99',
    category: 'shirts',
  },
  {
    id: 20,
    src: [jacket1, blank, blank],
    alt: 'jacket1',
    name: 'jacket',
    price: '$32.99',
    category: 'jackets',
  },
  {
    id: 21,
    src: [jacket1, blank, blank],
    alt: 'jacket1',
    name: 'jacket',
    price: '$32.99',
    category: 'jackets',
  },
  {
    id: 22,
    src: [jacket1, blank, blank],
    alt: 'jacket1',
    name: 'jacket',
    price: '$32.99',
    category: 'jackets',
  },
  {
    id: 23,
    src: [skirt1, blank, blank],
    alt: 'skirt1',
    name: 'skirt',
    price: '$38.99',
    category: 'skirts',
  },
  {
    id: 24,
    src: [socks1, blank, blank],
    alt: 'socks1',
    name: 'socks',
    price: '$7.99',
    category: 'Socks',
  },
  {
    id: 25,
    src: [shoe1, blank, blank],
    alt: 'shoe1',
    name: 'shoe1',
    price: '$42.99',
    category: 'Shoes',
  },
  {
    id: 26,
    src: [shoe2, blank, blank],
    alt: 'shoe2',
    name: 'shoe2',
    price: '$42.99',
    category: 'Shoes',
  },
  {
    id: 27,
    src: [neck1, blank, blank],
    alt: 'neck1',
    name: 'necklace1',
    price: '$208.99',
    category: 'Accessories',
  },
  {
    id: 27,
    src: [neck2, blank, blank],
    alt: 'neck2',
    name: 'necklace2',
    price: '$209.99',
    category: 'Accessories',
  },
  {
    id: 28,
    src: [socks1, blank, blank],
    alt: 'socks1',
    name: 'socks',
    price: '$7.99',
    category: 'Socks',
  },
  {
    id: 29,
    src: [socks1, blank, blank],
    alt: 'socks1',
    name: 'socks',
    price: '$7.99',
    category: 'Socks',
  },
  {
    id: 30,
    src: [socks1, blank, blank],
    alt: 'socks1',
    name: 'socks',
    price: '$7.99',
    category: 'Socks',
  },
  {
    id: 31,
    src: [neck1, blank, blank],
    alt: 'neck1',
    name: 'necklace1',
    price: '$208.99',
    category: 'Accessories',
  },
  {
    id: 32,
    src: [neck2, blank, blank],
    alt: 'neck2',
    name: 'necklace2',
    price: '$209.99',
    category: 'Accessories',
  },
]

export default ClothesData
